### ISSUE TITLE
Feature: use with standard SMTP servers 

### ISSUE THREAD

**Issue by buzzzo** [sublime-security/sublime-platform#101]
Project seems interesting but the integration seems to be oriented only to cloud providers. A good approach would be to create ad integration with SMTP server like postfix in order to use it as smtp relay. Is it a planned feature ?

**Comment by celevra** [comment]
+1

**Comment by cmprmsd** [comment]
++

**Comment by padey** [comment]
+++

**Comment by celevra** [comment]
But for what it does the best position for this tool is before of the user Mailbox!
Whay just scan the mailbox?
