### ISSUE TITLE
Running on ARM fails

### ISSUE THREAD

**Issue by DorianLoeben** [sublime-security/sublime-platform#107]
I tried running the auto install script on a raspberry pi 4 which barely meets the minimum requirements in the docs.
During installation it gives the warning for some images
`sublime_hydra The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested `
After the install during the health check afterwards, there is this output:
```
Checking health of containers...
exec /bin/sh: exec format error
exec /bin/sh: exec format error
exec /bin/sh: exec format error

** Successfully installed Sublime Platform! **
```
Afterwards some docker containers continue to restart with `exec /bin/sh: exec format error` in the logs
The documentation doesn't mention that all the docker images are only available for linux/amd64 and doesn't work for linux/arm64.
Failing Containers are:
```
sublime_strelka_frontend_1 
sublime_strelka_backend_1 
sublime_strelka_manager_1 
sublime_hydra 
```

If you want to support ARM I would suggest providing docker images for ARM architecture.
Or if you don't want to support ARM, I would like mentions of ARM incompatibility in the docs and an additional check in the preflight script.

**Comment by madirey** [comment]
Hi @Aneduna! As you pointed out above, we unfortunately do not currently support arm64 for all of our containers. I've added a [section to our docs](https://docs.sublimesecurity.com/docs/quickstart-docker#requirements) to make this more clear.

A few of our containers have dependencies that make them difficult to build for arm64, but the team is exploring whether or not this is something we can address in the future. Stay tuned, and thanks for your interest!

**Comment by cameron-dunn-sublime** [comment]
@DorianLoeben we just finished releasing ARM images for all services! Please go ahead and give the setup another shot and let us know if there are any issues.

**Comment by cameron-dunn-sublime** [comment]
Thanks @DorianLoeben! Really glad to hear everything on the setup side worked! I just updated the docs, thanks for pointing that out!

If you're still having troubles with the mail server, let's open up a fresh issue or join us [in Slack](https://join.slack.com/t/sublimecommunity/shared_invite/zt-1hhwosroy-LvflKNVE3HEtgIcbHdB1sw).
